package it.sudchiamanord.quizontheroad.utils;

public interface Tags
{
    String USER = "USER";
    String PASSWORD = "PASSWORD";

    String APP_FOLDER = "APP_FOLDER";

    String LOGIN_FRAGMENT = "LOGIN_FRAGMENT";
    String SEND_DATA_FRAGMENT = "SEND_DATA_FRAGMENT";

    String SESSION_KEY = "SESSION_KEY";
    String N_STAGES = "N_STAGES";
    String ID_IND = "ID_IND";

    String IS_LOGGED_IN = "IS_LOGGED_IN";
    String LOGIN_PROGRESS = "LOGIN_PROGRESS";

    String STAGE_NUMBER = "STAGE_NUMBER";
    String STAGE_LOCATION_CLUE = "STAGE_LOCATION_CLUE";
    String STAGE_MULTIMEDIA_CLUE = "STAGE_MULTIMEDIA_CLUE";
    String STAGE_TEST = "STAGE_TEST";
    String STAGE_STATUS = "STAGE_STATUS";
    String STAGE_CORRECT_POSITION = "CORRECT_POSITION";
    String STAGE_WAIT_POSITION_CONFIRMED = "WAIT_POSITION_CONFIRMED";
    String STAGE_POSITION_UPDATE_STATUS = "POSITION_UPDATE_STATUS";

    String RESOURCE_ABSOLUTE_PATH = "RESOURCE_ABSOLUTE_PATH";
    String RESOURCE_NAME = "FILE_NAME";
    String NOTIF_SUCCESS_TOAST = "NOTIF_SUCCESS_TOAST";
    String NOTIF_FAIL_TOAST = "NOTIF_FAIL_TOAST";
    String PROGRESS_DIALOG_TITLE = "PROGRESS_DIALOG_TITLE";
    String PROGRESS_DIALOG_MESSAGE = "PROGRESS_DIALOG_MESSAGE";
}
